#! /usr/bin/env python

import argparse

import workflow.laboratory as laboratory
import workflow.util.config as config


def _subparser_mesher(sp):
    parser = sp.add_parser(
        "mesher",
        help="runs the mesher",
        description="Runs the mesher on the given experiment",
    )
    parser.add_argument("experiment", type=str, help="name of the experiment")


def librarian_args(args: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Manages simulations in a specfem workspace."
    )
    sp = parser.add_subparsers(title="subcommands")
    # new
    _subparser_mesher(sp)

    return parser.parse_args(args)


if __name__ == "__main__":
    # print(laboratory.pi.get_experiment_list(verbose=True))
    # print(laboratory.pi.tasks_in_experiment("snell.FF", verbose=True))

    # laboratory.pi.full_run_experiment("snell.FF", verbose=True)

    default_experiment = config.get("lab.default_experiment")
    print(f'Running default experiment "{default_experiment}".')
    print(laboratory.pi.tasks_in_experiment(default_experiment, verbose=True))
    laboratory.pi.full_run_experiment(default_experiment, verbose=True)

    args = librarian_args()
